
//VIDEO GALLERY
(function(m){m.fn.vGallery=function(a){a=m.extend({menuWidth:100,menuHeight:350,menuSpace:0,randomise:"off",autoplay:"off",autoplayNext:"on",menu_position:"right",menuitem_width:"200",menuitem_height:"71",menuitem_space:"0",transition_type:"slideup",design_skin:"skin_default",videoplayersettings:""},a);this.each(function(){function v(a,b){var a=parseInt(Math.random()*b),c=0;for(j=0;j<l.length;j++)a==l[j]&&(c=1);if(1==c)v(0,b);else return l.push(a),a}function x(b){!1==is_ios()&&(("right"==a.menu_position||
"left"==a.menu_position)&&f.css({top:-((b.pageY-e.offset().top)/i*((a.menuitem_height+a.menuitem_space)*d-i))}),("bottom"==a.menu_position||"top"==a.menu_position)&&f.css({left:-((b.pageX-e.offset().left)/g*((a.menuitem_width+a.menuitem_space)*d-g))}))}function y(a){t(f.children().index(a.currentTarget))}function t(b){function d(){h.parent().children(".preloader").fadeOut("fast");"fade"==a.transition_type&&(c.children().eq(b).css({left:0,top:0}),-1<k&&c.children().eq(k).animate({opacity:"0"},1E3),
c.children().eq(b).css({opacity:"0"}),c.children().eq(b).animate({opacity:"1"},1E3));"slideup"==a.transition_type&&(-1<k&&(c.children().eq(k).animate({left:0,top:0},0),c.children().eq(k).animate({left:0,top:-i},700)),c.children().eq(b).animate({left:0,top:i},0),c.children().eq(b).animate({left:0,top:0},700));is_ios()&&-1<k&&"VIDEO"==c.children().eq(k).children().eq(0)[0].tagName&&c.children().eq(k).children().eq(0).get(0).pause();!is_ios()&&!is_ie8()&&-1<k&&epauseMovie(c.children().eq(k));u=!1;k=
b}if(!(k==b||!0==u)){var f=!1,e=c.children().eq(b),g=e.parent().children().index(e);e.hasClass("vplayer-tobe")&&(f=!0,a.videoplayersettings.videoWidth=n,a.videoplayersettings.videoHeight=r,"on"==a.autoplay&&0==g&&(a.videoplayersettings.autoplay="on"),"on"==a.autoplayNext&&0<g&&(a.videoplayersettings.autoplay="on"),e.vPlayer(a.videoplayersettings));u=!0;-1==k||!1==f?d():(h.parent().children(".preloader").fadeIn("fast"),setTimeout(d,1E3))}}var h=jQuery(this);m(this)[0].getAttribute("id");var d=0,o,
c,e,f,n,r,g,i,l=[],w=[],k=-1,p=0,s=0,u=!1;a.menuitem_width=parseInt(a.menuitem_width);a.menuitem_height=parseInt(a.menuitem_height);a.menuitem_space=parseInt(a.menuitem_space);d=jQuery(this).children().length;n=parseInt(jQuery(this).css("width"));r=parseInt(jQuery(this).css("height"));g=n;i=r;if(("right"==a.menu_position||"left"==a.menu_position)&&1<d)g+=a.menuitem_width+a.menuSpace;if(("bottom"==a.menu_position||"top"==a.menu_position)&&1<d)i+=a.menuitem_height+a.menuSpace;h.addClass(a.design_skin);
a.videoplayersettings.design_skin=a.design_skin;0==h.css("opacity")&&h.animate({opacity:1},1E3);h.parent().children(".preloader").fadeOut("fast");for(b=0;b<d;b++)w[b]=jQuery(this).children().eq(b),"on"==a.randomise?v(0,d):l[b]=b;h.append('<div class="sliderMain"><div class="sliderCon"></div></div>');h.append('<div class="navMain"><div class="navCon"></div></div>');o=jQuery(this).find(".sliderMain");c=jQuery(this).find(".sliderCon");is_ie8()&&c.addClass("sliderCon-ie8");e=jQuery(this).find(".navMain");
f=jQuery(this).find(".navCon");h.css({width:g,height:i});h.parent().hasClass("videogallery-con")&&h.parent().css({width:g,height:i});for(b=0;b<d;b++){var q=h.children().eq(l[b]).find(".menuDescription").html();h.children().eq(l[b]).find(".menuDescription").remove();null!=q&&(-1<q.indexOf("{ytthumb}")&&(q=q.split("{ytthumb}").join('<img src="http://img.youtube.com/vi/'+h.children().eq(l[b]).attr("data-src")+'/0.jpg" class="imgblock"/>')),f.append('<div><div class="navigationThumb-content">'+q+"</div></div>"),
f.children().eq(b).addClass("navigationThumb"),f.children().eq(b).css({width:a.menuitem_width,height:a.menuitem_height}),f.children().eq(b).click(y),"right"==a.menu_position||"left"==a.menu_position?f.children().eq(b).css({top:s}):f.children().eq(b).css({left:p}),s+=a.menuitem_height+a.menuitem_space,p+=a.menuitem_width+a.menuitem_space)}for(var b=0,b=0;b<d;b++)c.append(w[l[b]]);for(b=0;b<d;b++)is_ios();for(b=0;b<d;b++)c.children().eq(b).css({position:"absolute",top:"0px",left:p}),p+=g;o.css({width:g,
height:i});"right"==a.menu_position&&e.css({width:a.menuitem_width,height:i,left:n});"left"==a.menu_position&&(e.css({width:a.menuitem_width,height:i,left:0}),o.css({left:a.menuitem_width}));"bottom"==a.menu_position&&e.css({width:g,height:a.menuitem_height,top:r,left:0});"top"==a.menu_position&&(e.css({width:g,height:a.menuitem_height,top:0,left:0}),o.css({top:a.menuitem_height}));is_ios()&&e.css("overflow","auto");0!=a.menuSpace&&e.css({left:n+a.menuSpace});f.css({position:"relative"});jQuery(".navigationThumb").eq(0).height()*
d>i&&e.mousemove(x);s=0;1==d&&(jQuery(this).css({width:n}),e.hide());t(0);setInterval(function(){},5E3);m.fn.turnFullscreen=function(){jQuery(this).css({position:"static"});o.css({position:"static"})};m.fn.turnNormalscreen=function(){jQuery(this).css({position:"relative"});o.css({position:"relative"});for(b=0;b<d;b++)c.children().eq(b).css({position:"absolute"})};m.fn.vGallery.gotoItem=function(a){t(a)};return this})}})(jQuery);



//VIDEO PLAYER
var ytplayer,$=jQuery.noConflict();
(function(e){e.fn.vPlayer=function(c){c=e.extend({type:"normal",autoplay:"off",videoWidth:0,videoHeight:0,constrols_out_opacity:0,constrols_normal_opacity:0.9,design_scrubbarWidth:-201,insideGallery:!1,design_skin:"skin_default",design_background_offsetw:0},c);this.each(function(){function s(){b.find(".preview").hide();f.children().eq(0).css("visibility","hidden");f.children().eq(1).css("visibility","hidden");f.children().eq(2).css("visibility","visible");f.children().eq(3).css("visibility","visible");
"normal"==c.type&&d.play();"youtube"==c.type&&d.playVideo();b.children(".video-description").animate({opacity:0},500);t=!0}function z(){f.children().eq(0).css("visibility","visible");f.children().eq(1).css("visibility","visible");f.children().eq(2).css("visibility","hidden");f.children().eq(3).css("visibility","hidden");"normal"==c.type&&d.pause();"youtube"==c.type&&d.pauseVideo&&d.pauseVideo();b.children(".video-description").animate({opacity:1},500);t=!1}function A(){function a(q,f){b.css({width:q,
height:f});e(d).css({width:q,height:f});b.find(".background").css({width:q+parseInt(c.design_background_offsetw)});b.find(".preview").children().eq(0).css({width:q,height:f});i.css({width:q});is_ie8()&&i.css({position:"absolute",top:0,left:0});scrubbar=b.find(".scrubbar").children();scrubbar.eq(0).width(q+c.design_scrubbarWidth);E=parseInt(i.find(".infoText").css("left"));parseInt(i.find(".infoText").css("top"))}function F(a){var e=b.find(".volumecontrols").children();0<=a&&("normal"==c.type&&(d.volume=
a),"youtube"==c.type&&d.setVolume(100*a));e.eq(2).width(a*e.eq(1).width());null!=localStorage&&localStorage.setItem("volumeIndex",a)}function p(a){var a=Math.round(a),b=0;if(0<a){for(;59<a;)b++,a-=60;return""+((10>b?"0":"")+b+":"+(10>a?"0":"")+a)}return"00:00"}null!=localStorage&&(G=null===localStorage.getItem("volumeIndex")?1:localStorage.getItem("volumeIndex"));b.append('<div class="controls"></div>');i=b.find(".controls");i.css("opacity",c.constrols_normal_opacity);0==h&&(h=e(d).width(),j=e(d).height());
l=h;n=j;b.css({width:h,height:j});void 0!=b.attr("data-videoTitle")&&(b.append('<div class="video-description"></div>'),b.children(".video-description").append('<div class="video-title">'+b.attr("data-videoTitle")+"</div>"),""!=B&&b.children(".video-description").append('<div class="video-subdescription">'+B+"</div>"),b.find(".video-subdescription").css("width",0.7*h));"absolute"!=b.css("position")&&b.css("position","relative");"normal"==c.type&&e(d).css({position:"absolute","background-color":"#000000"});
i.append('<div class="background"></div>');i.append('<div class="playcontrols"></div>');i.append('<div class="scrubbar"></div>');i.append('<div class="timetext"></div>');i.append('<div class="volumecontrols"></div>');i.append('<div class="fscreencontrols"></div>');void 0!=b.attr("data-img")&&b.append('<div class="preview"><img src="'+b.attr("data-img")+'"/></div>');b.find(".info");r=b.find(".infoText");b.find(".info").click(function(){r=b.find(".infoText");if(r.css("opacity")==0){r.animate({left:"0",
opacity:"0"},{queue:false,duration:0});r.animate({left:E,opacity:"1"},{queue:false,duration:700})}else r.animate({left:l,opacity:"0"},{queue:false,duration:700})});f=b.find(".playcontrols");f.append('<div class="playSimple"></div>');f.append('<div class="playHover"></div>');f.append('<div class="stopSimple"></div>');f.append('<div class="stopHover"></div>');f.click(function(){u=false;c.type=="normal"&&d.paused&&(u=true);c.type=="youtube"&&d.getPlayerState&&d.getPlayerState()==2&&(u=true);if(is_ie8())if(C){s();
C=false}else{z();C=true}else u?s():z()});f.hover(function(){f.children().eq(1).animate({opacity:1},{queue:false,duration:300});f.children().eq(3).animate({opacity:1},{queue:false,duration:300})},function(){f.children().eq(1).animate({opacity:0},{queue:false,duration:300});f.children().eq(3).animate({opacity:0},{queue:false,duration:300})});scrubbar=b.find(".scrubbar");scrubbar.append('<div class="scrub-bg"></div>');scrubbar.append('<div class="scrub"></div>');scrubbar.click(function(a){scrubbar=b.find(".scrubbar");
t==false?z():s();if(c.type=="normal"){m=d.duration;d.currentTime=(a.pageX-scrubbar.offset().left)/scrubbar.children().eq(0).width()*m}if(c.type=="youtube"){m=d.getDuration();d.seekTo((a.pageX-scrubbar.offset().left)/scrubbar.children().eq(0).width()*m)}});setInterval(function(){scrubbar=b.find(".scrubbar");if(c.type=="normal"){m=d.duration;v=d.currentTime}if(c.type=="youtube"&&d.getDuration){m=d.getDuration();v=d.getCurrentTime()}k=v/m*scrubbar.children().eq(0).width();scrubbar.children().eq(1).width(k);
b.find(".timetext").html('<font color="#FFFFFF" size="1px">'+p(v)+'</font><font color="gray" size="1px">/'+p(m)+"</font>")},100);g=b.find(".volumecontrols");g.append('<div class="volumeicon"></div>');g.append('<div class="volume_static"></div>');g.append('<div class="volume_active"></div>');g.append('<div class="volume_cut"></div>');b.find(".volumecontrols").click(function(a){g=b.find(".volumecontrols").children();if(a.pageX-g.eq(1).offset().left>=0){k=a.pageX-g.eq(1).offset().left;g.eq(2).css("visibility",
"visible");g.eq(3).css("visibility","hidden");F(k/g.eq(1).width())}else if(g.eq(3).css("visibility")=="hidden"){w=d.volume;if(c.type=="normal")d.volume=0;c.type=="youtube"&&d.setVolume(0);g.eq(3).css("visibility","visible");g.eq(2).css("visibility","hidden")}else{console.log(w);if(c.type=="normal")d.volume=w;c.type=="youtube"&&d.setVolume(w);g.eq(3).css("visibility","hidden");g.eq(2).css("visibility","visible")}});o=b.find(".fscreencontrols");o.append('<div class="full"></div>');o.append('<div class="fullHover"></div>');
o.click(function(){l=e(window).width();n=e(window).height();if(x==0){x=1;jQuery("body").css("overflow","hidden");l=e(window).width();n=e(window).height();b.css({position:"fixed","z-index":9999,left:"0px",top:"0px",width:l,height:n});a(l,n);c.insideGallery==true&&jQuery(this).parent().parent().parent().parent().parent().turnFullscreen()}else{x=0;e("body").css("overflow",H);b.css({position:"relative","z-index":"auto",left:"0px",top:"0px",width:h,height:j});a(h,j);c.insideGallery==true&&jQuery(this).parent().parent().parent().parent().parent().turnNormalscreen()}});
o.hover(function(){o.children().eq(1).animate({opacity:1},{queue:false,duration:300})},function(){o.children().eq(1).animate({opacity:0},{queue:false,duration:300})});a(h,j);F(G);"on"==D&&s();b.mouseout(function(){i.animate({opacity:c.constrols_out_opacity},{queue:false,duration:200})});b.mouseover(function(){i.animate({opacity:c.constrols_normal_opacity},{queue:false,duration:200})});e(window).resize(function(){if(x===1){l=e(window).width();n=e(window).height();a(l,n)}})}var b,i,h,j,l,n,d,k=0,x=
0,p,w,G,E,t=!1,D="off",g,o,f,r,u=!1,C=!0,m=0,v=0,I="",y="",J="",B="",H="auto;";b=jQuery(this);e(this)[0].getAttribute("id");H=e("body").css("overflow");D=c.autoplay;h=c.videoWidth;j=c.videoHeight;if(b.hasClass("vplayer-tobe")){var a=b;a.removeClass("vplayer-tobe");a.addClass("vplayer");a.addClass(c.design_skin);0<a.find(".videoDescription").length&&(B=a.find(".videoDescription").html(),a.find(".videoDescription").remove());I=a.attr("data-type");J=a.attr("data-src");y=a.attr("data-sourceflash");void 0==
a.attr("data-sourceflash")&&(y=a.attr("data-sourcemp4"));if(is_ie8()){a.addClass("vplayer-ie8");"youtube"!=I?a.append('<div><object type="application/x-shockwave-flash" data="preview.swf" width="'+h+'" height="'+j+'" id="flashcontent" style="visibility: visible;"><param name="movie" value="preview.swf"><param name="menu" value="false"><param name="allowScriptAccess" value="always"><param name="scale" value="noscale"><param name="allowFullScreen" value="true"><param name="wmode" value="opaque"><param name="flashvars" value="video='+
y+'"></object></div>'):(c.type="youtube",a.children().remove(),k="ytplayer"+J,a.append('<iframe width="'+h+'" height="'+j+'" src="http://www.youtube.com/embed/'+a.attr("data-src")+'" frameborder="0" allowfullscreen></iframe>'),a.attr("data-ytid",k));return}if(is_ios()){a.append("<video controls preload></video>");a.children().eq(0).attr("width",h);a.children().eq(0).attr("height",j);"youtube"!=a.attr("data-type")?("ie8/flash"==c.type,void 0!=a.attr("data-sourcemp4")&&a.children().eq(0).append('<source src="'+
a.attr("data-sourcemp4")+'" type="video/mp4"/>')):(c.type="youtube",a.children().remove(),k="ytplayer"+a.attr("data-src"),a.append('<iframe width="'+h+'" height="'+j+'" src="http://www.youtube.com/embed/'+a.attr("data-src")+'" frameborder="0" allowfullscreen></iframe>'));return}!is_ie8()&&!is_ios()&&(a.append("<video controls preload></video>"),"youtube"!=a.attr("data-type")?(void 0!=a.attr("data-sourcemp4")&&(a.children().eq(0).append('<source src="'+a.attr("data-sourcemp4")+'" type="video/mp4"/>'),
is_ie9()&&a.html('<video controls preload><source src="'+a.attr("data-sourcemp4")+'" type="video/mp4"/></video>')),void 0!=a.attr("data-sourceogg")&&a.children().eq(0).append('<source src="'+a.attr("data-sourceogg")+'" type="video/ogg"/>'),void 0!=a.attr("data-sourcewebm")&&a.children().eq(0).append('<source src="'+a.attr("data-sourcewebm")+'" type="video/webm"/>'),void 0!=a.attr("data-sourceflash")&&!(e.browser.msie&&8<e.browser.version)&&a.children().eq(0).append('<object type="application/x-shockwave-flash" data="preview.swf" width="'+
h+'" height="'+j+'" id="flashcontent" style="visibility: visible;"><param name="movie" value="preview.swf"><param name="menu" value="false"><param name="allowScriptAccess" value="always"><param name="scale" value="noscale"><param name="allowFullScreen" value="true"><param name="wmode" value="opaque"><param name="flashvars" value="video='+y+'"></object>')):(c.type="youtube",a.children().remove(),k="ytplayer"+a.attr("data-src"),a.append('<object type="application/x-shockwave-flash" data="http://www.youtube.com/apiplayer?enablejsapi=1&version=3&playerapiid='+
k+'" width="'+h+'" height="'+j+'" id="'+k+'" style="visibility: visible;"><param name="movie" value="http://www.youtube.com/apiplayer?enablejsapi=1&version=3"><param name="menu" value="false"><param name="allowScriptAccess" value="always"><param name="scale" value="noscale"><param name="allowFullScreen" value="true"><param name="wmode" value="opaque"><param name="flashvars" value=""></object>'),a.attr("data-ytid",k)))}0==b.css("opacity")&&b.animate({opacity:1},1E3);"normal"==c.type?(d=b.children().eq(0)[0],
d.controls=!1):d=b.children().eq(0)[0];"on"==D&&(t=!0);p=setInterval(function(){if(c.type=="youtube"&&d.getPlayerState){if(is_ie8()){clearInterval(p);setTimeout(A,1E3);return}if(d.getPlayerState()>-1){clearInterval(p);A()}}if(c.type=="normal"&&Number(d.readyState)>=3){clearInterval(p);A()}},50);epauseMovie=function(a){if(!is_ios()){var b=a.find(".playcontrols").children();b.eq(0).css("visibility","visible");b.eq(1).css("visibility","visible");b.eq(2).css("visibility","hidden");b.eq(3).css("visibility",
"hidden");a.find("video").length>0&&a.find("video")[0].pause();a.attr("data-ytid")!=void 0&&document.getElementById(a.attr("data-ytid")).pauseVideo()}}})}})(jQuery);function onYouTubePlayerReady(e){ytplayer=document.getElementById(e);ytplayer.addEventListener("onStateChange","onytplayerStateChange");e=e.substr(8);ytplayer.loadVideoById(e);ytplayer.pauseVideo()}function onytplayerStateChange(){}
function is_ios(){return-1!=navigator.platform.indexOf("iPhone")||-1!=navigator.platform.indexOf("iPod")||-1!=navigator.platform.indexOf("iPad")}function is_ie9(){return $.browser.msie&&9==parseInt($.browser.version)?!0:!1}function is_ie8(){return $.browser.msie&&9>parseInt($.browser.version)?!0:!1};